FROM golang:1-alpine3.16 AS builder

RUN apk add --no-cache git ca-certificates build-base su-exec olm-dev bash jq yq curl

COPY . /build
WORKDIR /build
RUN go build -o /usr/bin/mautrix-discord

# Setup development stack using gow
RUN go install github.com/mitranim/gow@latest
RUN echo 'gow run /build $@' > /usr/bin/mautrix-discord \
    && chmod +x /usr/bin/mautrix-discord
VOLUME /data
